### ISSUE TITLE
too little brown; too much cyan

### ISSUE THREAD

**Issue by srid** [SavchenkoValeriy/emacs-chocolate-theme#1]
On Linux with graphical emacs while hacking on Haskell I don't see as much brown as expected. Screenshot for illustration:

![image](https://user-images.githubusercontent.com/3998/61664294-7b023d80-aca0-11e9-9e46-48891d7e21d7.png)

**Comment by srid** [comment]
Code in screenshot: https://github.com/srid/rib/blob/master/src/Rib/Pandoc.hs

with `haskell-mode`.

**Comment by SavchenkoValeriy** [comment]
@srid I see. 
First of all, thanks for the feedback.
`chocolate-theme` uses this cyan color for functions and types. In most languages, it looks fine, but it looks like Haskell is just straight up functions/types. I think I can tweak specifically for Haskell mode to fix this.
PS many thanks also for the code snippet to test!

**Comment by SavchenkoValeriy** [comment]
Is this version of Haskell **chocolatey** enough? :-) 
<img width="892" alt="Screenshot 2019-07-23 at 00 13 05" src="https://user-images.githubusercontent.com/1611696/61665855-c1768d00-acde-11e9-9de5-8c020adbfe01.png">

**Comment by SavchenkoValeriy** [comment]
BTW, I dunno what's up with your background, but it's definitely not from *chocolate-theme*

**Comment by SavchenkoValeriy** [comment]
@srid is it any good? Please check the screenshot above.
I would have to merge this brunch as-is without your feedback.

**Comment by srid** [comment]
@SavchenkoValeriy Oops, I missed your comment (got no notification from Github). 

It is looking better, but the color spectrum is kind of bland now. Adding the cyan (from README's screenshot) back, in right proportions, would help I think.

**Comment by srid** [comment]
The cyan should be applied to function/class names more than parentheses. Haskellers don't particularly care about unique faces for brackets and parentheses. :-)

**Comment by SavchenkoValeriy** [comment]
@srid functions are still cyan, I changed only types and constructors. See the screenshot:
<img width="820" alt="Screenshot 2019-07-28 at 17 56 13" src="https://user-images.githubusercontent.com/1611696/62008915-2871c700-b161-11e9-8bbc-914fa170277b.png">

**Comment by srid** [comment]
Okay, looks good!

**Comment by SavchenkoValeriy** [comment]
Great! Merging it then
