### ISSUE TITLE
Chocolate not working well with emacs 29

### ISSUE THREAD

**Issue by M1ndo** [SavchenkoValeriy/emacs-chocolate-theme#15]
I'm not sure if it is an emacs issue but other themes seem to be working well with emacs.
Here's a screenshot:
![chocolate_theme](https://user-images.githubusercontent.com/44820142/150698463-7d4efcd7-ccab-4748-9286-fe2493a4161e.png)

**Comment by SavchenkoValeriy** [comment]
Hmm, I've used it on Emacs 29 myself, didn't have any problems. This screenshot doesn't have any signs of chocolate theme. How did you install it?

**Comment by M1ndo** [comment]
> Hmm, I've used it on Emacs 29 myself, didn't have any problems. This screenshot doesn't have any signs of chocolate theme. How did you install it?

I installed it manually, it didn't work because `autothemer` wasn't installed.
Please update your README.org page and `autothemer` as dependency.
