### ISSUE TITLE
Support Centaur tabs?

### ISSUE THREAD

**Issue by localredhead** [SavchenkoValeriy/emacs-chocolate-theme#4]
https://github.com/ema2159/centaur-tabs

It's a nice to have.

**Comment by localredhead** [comment]
Some themes are starting to adopt centaur tabs to make them look the same as the theme.  Looks like this right now ![image](https://user-images.githubusercontent.com/152448/62153908-9b9b4a80-b2d3-11e9-867e-c675159cbec4.png)

not really a big deal.  Like I said it would be a nice to have. 

Awesome work so far.

**Comment by SavchenkoValeriy** [comment]
@localredhead Thanks for your kind words!
I will definitely take a look at it in the next few days and suggest a solution.

**Comment by SavchenkoValeriy** [comment]
@localredhead I've tried to play around with _centaur tabs_. And here is what I've got so far:
<img width="772" alt="Screenshot 2019-08-03 at 20 18 15" src="https://user-images.githubusercontent.com/1611696/62415023-2eb5e680-b62c-11e9-9099-7c42c138ad8f.png">

Showing selected non-modified:
<img width="631" alt="Screenshot 2019-08-03 at 20 18 41" src="https://user-images.githubusercontent.com/1611696/62415039-5f961b80-b62c-11e9-9a15-7529c8bc0a10.png">
...and selected modified:
<img width="619" alt="Screenshot 2019-08-03 at 20 19 06" src="https://user-images.githubusercontent.com/1611696/62415043-691f8380-b62c-11e9-9527-2c1f86316159.png">

What do you think about this solution?

**Comment by ema2159** [comment]
@localredhead hey there fellow ginger programming man, it's nice to see some one of my kind around 😂!

**Comment by SavchenkoValeriy** [comment]
@localredhead  is it any good? Please check the screenshots above.
I'll have to merge this brunch as-is without your feedback.

**Comment by ema2159** [comment]
For me it looks perfect

**Comment by localredhead** [comment]
My apologies for the delayed response as I was vacationing without connectivity :) 

Just updated and the tabs look great.  Thank you!
