### ISSUE TITLE
Marking and highlighting things is problematic if hl-line mode is used globally 

### ISSUE THREAD

**Issue by localredhead** [SavchenkoValeriy/emacs-chocolate-theme#5]
![image](https://user-images.githubusercontent.com/152448/62153027-b7055600-b2d1-11e9-92e9-fb0690af0042.png)

In the screen shot I'm highlighting that row of json with market-set (as if I'm going to yank or paste).  I also have hl-line mode on.  With hl-line themed the same as the region I have to customize the theme to make one or the other distinct.

Digging into the configs, Transitional Mark mode uses whatever is themed in the `Region` face.  
![image](https://user-images.githubusercontent.com/152448/62153507-aef9e600-b2d2-11e9-8d71-3f9c6e384793.png)

Region:
![image](https://user-images.githubusercontent.com/152448/62153584-e4063880-b2d2-11e9-881e-437a956b2c33.png)

This is also the same face that is used for `hl-line` face is set to:
![image](https://user-images.githubusercontent.com/152448/62153399-735f1c00-b2d2-11e9-9ba9-46146db557a3.png)

**Comment by localredhead** [comment]
Also thank you for all the great work on this theme.  I like this color palette a lot.   🏅

**Comment by SavchenkoValeriy** [comment]
@localredhead Thank you very much for your kind words! I really appreciate it 😳 

As for the topic, I see the problem. What about the following solution (I introduced a new color in between background and region):
<img width="772" alt="Screenshot 2019-07-31 at 10 32 39" src="https://user-images.githubusercontent.com/1611696/62192767-e6be6780-b37e-11e9-90a1-9c0d6f8346df.png">
`hl-line` on its own looks like this then:
<img width="659" alt="Screenshot 2019-07-31 at 10 37 06" src="https://user-images.githubusercontent.com/1611696/62192930-4c125880-b37f-11e9-922b-57362c25ab6d.png">

This solution, though, might be too subtle, so here's a bit brighter option:
<img width="772" alt="Screenshot 2019-07-31 at 10 43 56" src="https://user-images.githubusercontent.com/1611696/62193285-1fab0c00-b380-11e9-901b-8a7265a04170.png">
<img width="655" alt="Screenshot 2019-07-31 at 10 42 40" src="https://user-images.githubusercontent.com/1611696/62193193-f5f1e500-b37f-11e9-8cfe-439df51150a6.png">

What do you think?

**Comment by localredhead** [comment]
I think the brighter option looks quite good!

**Comment by SavchenkoValeriy** [comment]
Great to hear!
