### ISSUE TITLE
Make mode-line more distinct

### ISSUE THREAD

**Issue by ghost** [SavchenkoValeriy/emacs-chocolate-theme#6]
Make mode-line more distinguishable from the background and also make the mode-line-inactive more readable. Currently it looks like this:

<img width="656" alt="Screen Shot 2019-08-09 at 15 15 39" src="https://user-images.githubusercontent.com/22227390/62800086-df066d80-bab8-11e9-9268-7eed2cddb208.png">

**Comment by SavchenkoValeriy** [comment]
Oh, I use a non-default modeling and didn't encounter this issue. I'll look into it asap.

**Comment by SavchenkoValeriy** [comment]
@arzoriac here is what I ended up with: brighter one for the active and dimmer one for the inactive mode-line.

<img width="969" alt="Screenshot 2019-08-11 at 11 48 36" src="https://user-images.githubusercontent.com/1611696/62831863-0cc0f300-bc2e-11e9-90c4-3b7fbf0e5f6b.png">

How do you like? If this solution is fine, I'll merge it into the master branch.

**Comment by ghost** [comment]
Perfect!
