### ISSUE TITLE
Code additions within magit are not highlighted a different color, but subtractions are

### ISSUE THREAD

**Issue by localredhead** [SavchenkoValeriy/emacs-chocolate-theme#7]
![image](https://user-images.githubusercontent.com/152448/63125915-c5639b00-bf7c-11e9-84e8-898648fcf805.png)

I would expect to see a green line where it shows the `+` next to the addition

**Comment by localredhead** [comment]
I see the green updates when I click on the modified section to activate it...  in the un-activated state is where I see the issue 

Activated:  
![image](https://user-images.githubusercontent.com/152448/63126109-20958d80-bf7d-11e9-9378-a254b281d82f.png)

**Comment by SavchenkoValeriy** [comment]
Thanks for noticing that, I never had a chance (for some reason). I'll have a look at it in the next few days!

**Comment by SavchenkoValeriy** [comment]
@localredhead ✅ 

<img width="870" alt="Screenshot 2019-08-18 at 10 54 44" src="https://user-images.githubusercontent.com/1611696/63221782-a7797e80-c1a6-11e9-8d40-f20eb216b70b.png">
