### ISSUE TITLE
info:modeline

### ISSUE THREAD

**Issue by ratnesh1729** [SavchenkoValeriy/emacs-chocolate-theme#8]
That's a great theme. 
Curious to know what is the modeline you used in the top screenshot ?
Thanks!

**Comment by SavchenkoValeriy** [comment]
@ratnesh1729 Thanks! 
I already answered this in one of the issues and on reddit, so I guess I should add this info into README.
It is [spaceline-all-the-icons](https://github.com/domtronn/spaceline-all-the-icons.el).
